spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/noticationhub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: "cambia-este-secreto-por-uno-largo-y-aleatorio"
  expiration: 3600
